### ISSUE TITLE
1.get_data_loader

### ISSUE THREAD

**Issue by songhune** [NESAP-STL/nesap-stl#11]
별로 쓸모 없을 지도 모르지만 한게 아깝기 때문에...

sea 데이터 기준으로 했습니다. climate도 같을지도..?
1.get_data_loader	//데이터를 train_data_loader, valid_data_loader로 분리

get_data_loader	(datasets/_init_.py)
	get_datasets	(datasets/climate.py)
		1.데이터 로드
		2.데이터 크기 조정
		data size   -> (14389,70,125) = (T,H,W) ==(time, height, width)??
                    -> (14389,68,120) //124로 안 하고 120으로 자른 이유가 있나요? patch_size==4라 124도 될 것 같은데
                    -> (1,14389,1,68,120) // reshape_patch 돌리려고, dummy batch dim,channel dim 추가
        reshape_patch   (utils/preprocess.py)
            patch_size=4
            data    -> (1,14389, 1, 68, 120)
                    -> (1, 14389, 16, 17, 30)   //channel_dim *= 4*4, W/=4, T/=4
                                                //channel_dim이 확실한 건 아니고 추측하는 겁니다.
                                                //channel을 여기서 적용하는 게 맞는지, 왜 적용하는 건지는 잘 모르겠습니다.
            return data 크기 조정한 결과
        
        get_datasets cont.	(datasets/climate.py)
        n_train_seq = 10255 = 10240+16-1
        train_data  -> data[0:10255]        //10256
        valid_data  -> data[10256:14388]    //4133
        train_set = train_data + seq_len(==16)
        valid_set = valid_data + seq_len(==16)
        
        return train_set, valid_set, {} //{}는 loader_args에 해당
    
    get_data_loader	cont. (datasets/_init_.py)
    train_sampler, valid_sampler    //sampler distribution_sampler 사용
                                    //sampler가 학습할 때 sample을 분산처리? 해서 제공하는 역할인 것 같은데 맞나요?
    train_loader = DataLoader(train_dataset, batch_size, sampler, shuffle, **loader_args)
    valid_loader = DataLoader(valid_dataset, batch_size, sampler, **loader_args)
    //train_datasets -> (10256,16,17,30), seq_len = 16
    //batch_size = 4
    //sampler = train_sampler = distribution_sampler?
    //shuffle =T,F?
    //loader_args = {}  loader_args는 어떤 역할?
    
    return train_loader, valid_loader

의문점
1. reshape_size 전에 data를 (14389, 68, 124)가 아니라 (14389,68,120)으로 자른 이유가 있나요?
2. reshape_size 결과인 data -> (14389, 16, 17, 30)에서 16이 channel_dim이 맞는지? channel은 정확히 어떤 역할?
3. loader_args는 DataLoader 찾아보니까 batch_sample, num_workers, collate_fn등을 말하는 것 같은데 맞나요?

_Originally posted by @ks1101 in https://github.com/NESAP-STL/nesap-stl/issues/8#issuecomment-885350306_

**Comment by songhune** [comment]
의문점 1.
_reshape_size 전에 data를 (14389, 68, 124)가 아니라 (14389,68,120)으로 자른 이유가 있나요?_
> 
`Traceback (most recent call last):
  File "C:/Users/songh/PycharmProjects/nesap-stl/train.py", line 110, in <module>
    main()

  File "C:/Users/songh/PycharmProjects/nesap-stl/train.py", line 74, in main
    train_data_loader, valid_data_loader = get_data_loaders(distributed=distributed, **config['data'])

  File "C:\Users\songh\PycharmProjects\nesap-stl\datasets\__init__.py", line 23, in get_data_loaders
    train_dataset, valid_dataset, loader_args = get_datasets(name=name, **dataset_args)

  File "C:\Users\songh\PycharmProjects\nesap-stl\datasets\__init__.py", line 13, in get_datasets
    return module.get_datasets(**data_args)

  File "C:\Users\songh\PycharmProjects\nesap-stl\datasets\climate.py", line 58, in get_datasets
    data = reshape_patch(data, patch_size)

  File "C:\Users\songh\PycharmProjects\nesap-stl\utils\preprocess.py", line 14, in reshape_patch
    a = np.reshape(img_tensor, [batch_size, seq_length, num_channels,img_height//patch_size, patch_size,img_width//patch_size, patch_size])

  File "<__array_function__ internals>", line 6, in reshape

  File "C:\Users\songh\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 301, in reshape

    return _wrapfunc(a, 'reshape', newshape, order=order)

  File "C:\Users\songh\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)

**ValueError: cannot reshape array of size 124896520 into shape (1,14389,1,17,4,31,4)`**

shape changing issue

**Comment by songhune** [comment]
의문점 2
_reshape_size 결과인 data -> (14389, 16, 17, 30)에서 16이 channel_dim이 맞는지? channel은 정확히 어떤 역할?_
> 16은 channel dimension이 맞습니다
>channel이란?
일단 본 프로젝트에서 최소 3개의 서로 다른 channel이 존재하는걸 확인해야 됩니다.
preprocess.py  ln: 19 에 보시면 patch tensor가 있습니다.
channel = 16은 patch size(4)의 제곱이라 할 수 있겠네요.

**Comment by songhune** [comment]
의문점 3
_loader_args는 DataLoader 찾아보니까 batch_sample, num_workers, collate_fn등을 말하는 것 같은데 맞나요?_
>네, torch에서 기본적으로 제공하는 기능은 그것들이 맞습니다. 본 프로젝트에선 구현되어있지 않네요
