### ISSUE TITLE
[Visualization] Adopting state_dict for showing off

### ISSUE THREAD

**Issue by songhune** [NESAP-STL/nesap-stl#7]
Once we finish our trainings in vanilla code, we were able to get checkpoints(actually, state_dict) by trainers-base.py,
```{.python}
def write_checkpoint(self, checkpoint_id):
    assert self.output_dir is not None        
    checkpoint_file = self._get_checkpoint_file(checkpoint_id)       
    os.makedirs(os.path.dirname(checkpoint_file), exist_ok=True)        
    torch.save(self.state_dict(), checkpoint_file) #like this
```
and we get our pth files.
After that, we'll need to visualize this parameters to given dataset with sampling(which is already made), and I guess it  needst to pass through 

```{.python}
class PredRNNPP(torch.nn.Module):
    """The PredRNN++ model"""

    def __init__(self, filter_size=3, num_dims=2,
                 num_hidden=[128, 64, 64, 64, 16]):
        super().__init__()

        self.clstm = CausalLSTMStack(filter_size=filter_size,
                                     num_dims=num_dims,
                                     channels=num_hidden)
        if num_dims == 2:
            self.decoder = torch.nn.Conv2d(num_hidden[-1], num_hidden[-1], 1)
        elif num_dims == 3:
            self.decoder = torch.nn.Conv3d(num_hidden[-1], num_hidden[-1], 1)
        else:
            raise ValueError(f'num_dims value {num_dims} not allowed')

    def forward(self, x):

        # Initialize hidden states
        h, c, m, z = [None]*4
        outputs = []

        # Loop over the sequence
        for t in range(x.shape[1]):
            h, c, m, z = self.clstm(x[:,t], h, c, m, z)
            outputs.append(self.decoder(h[-1])) #.permute(0, -1, 1, 2)

        # Stack outputs along time axis
        return torch.stack(outputs, dim=1)

```
's forward method. will that be correct? or am i missed sth?

**Comment by songhune** [comment]
What I've done so far
1. retrieve model parameters with visualization(which is no use for this time)
2. running climate data, not just sea_level data
3. making animation clip for next frame(or are they clips?), once we get to the predicted tensors

**Comment by songhune** [comment]
2021-07-02 02:22:15,666 INFO Number of parameters: 298696
Traceback (most recent call last):
  File "/Users/hanseunghyeon/Documents/GitHub/nesap-stl/train.py", line 113, in <module>
    main()
  File "/Users/hanseunghyeon/Documents/GitHub/nesap-stl/train.py", line 92, in main
    model.load_state_dict(torch.load('./outcomes/checkpoint_031.pth.tar',map_location=torch.device('cpu'))['model'])
  File "/Users/hanseunghyeon/Library/Python/3.7/lib/python/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PredRNNPP:
	Missing key(s) in state_dict: "clstm.lstms.4.ln_h.weight", "clstm.lstms.4.ln_h.bias", "clstm.lstms.4.ln_c.weight", "clstm.lstms.4.ln_c.bias", "clstm.lstms.4.ln_m.weight", "clstm.lstms.4.ln_m.bias", "clstm.lstms.4.ln_x.weight", "clstm.lstms.4.ln_x.bias", "clstm.lstms.4.ln_c2.weight", "clstm.lstms.4.ln_c2.bias", "clstm.lstms.4.ln_o.weight", "clstm.lstms.4.ln_o.bias", "clstm.lstms.4.conv_h.weight", "clstm.lstms.4.conv_h.bias", "clstm.lstms.4.conv_c.weight", "clstm.lstms.4.conv_c.bias", "clstm.lstms.4.conv_m.weight", "clstm.lstms.4.conv_m.bias", "clstm.lstms.4.conv_x.weight", "clstm.lstms.4.conv_x.bias", "clstm.lstms.4.conv_c2.weight", "clstm.lstms.4.conv_c2.bias", "clstm.lstms.4.conv_o.weight", "clstm.lstms.4.conv_o.bias", "clstm.lstms.4.conv_h2.weight", "clstm.lstms.4.conv_h2.bias". 
	size mismatch for clstm.lstms.0.ln_h.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for clstm.lstms.0.ln_h.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for clstm.lstms.0.ln_c.weight: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for clstm.lstms.0.ln_c.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for clstm.lstms.0.ln_m.weight: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for clstm.lstms.0.ln_m.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for clstm.lstms.0.ln_x.weight: copying a param with shape torch.Size([56]) from checkpoint, the shape in current model is torch.Size([896]).
	size mismatch for clstm.lstms.0.ln_x.bias: copying a param with shape torch.Size([56]) from checkpoint, the shape in current model is torch.Size([896]).
	size mismatch for clstm.lstms.0.ln_c2.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for clstm.lstms.0.ln_c2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for clstm.lstms.0.ln_o.weight: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for clstm.lstms.0.ln_o.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for clstm.lstms.0.conv_h.weight: copying a param with shape torch.Size([32, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 128, 3, 3]).
	size mismatch for clstm.lstms.0.conv_h.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for clstm.lstms.0.conv_c.weight: copying a param with shape torch.Size([24, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 128, 3, 3]).
	size mismatch for clstm.lstms.0.conv_c.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for clstm.lstms.0.conv_m.weight: copying a param with shape torch.Size([24, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 16, 3, 3]).
	size mismatch for clstm.lstms.0.conv_m.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for clstm.lstms.0.conv_x.weight: copying a param with shape torch.Size([56, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([896, 16, 3, 3]).
	size mismatch for clstm.lstms.0.conv_x.bias: copying a param with shape torch.Size([56]) from checkpoint, the shape in current model is torch.Size([896]).
	size mismatch for clstm.lstms.0.conv_c2.weight: copying a param with shape torch.Size([32, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 128, 3, 3]).
	size mismatch for clstm.lstms.0.conv_c2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for clstm.lstms.0.conv_o.weight: copying a param with shape torch.Size([8, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for clstm.lstms.0.conv_o.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for clstm.lstms.0.conv_h2.weight: copying a param with shape torch.Size([8, 16, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 256, 1, 1]).
	size mismatch for clstm.lstms.0.conv_h2.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for clstm.lstms.1.ln_h.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.1.ln_h.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.1.ln_c.weight: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.1.ln_c.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.1.ln_m.weight: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.1.ln_m.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.1.ln_x.weight: copying a param with shape torch.Size([112]) from checkpoint, the shape in current model is torch.Size([448]).
	size mismatch for clstm.lstms.1.ln_x.bias: copying a param with shape torch.Size([112]) from checkpoint, the shape in current model is torch.Size([448]).
	size mismatch for clstm.lstms.1.ln_c2.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.1.ln_c2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.1.ln_o.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for clstm.lstms.1.ln_o.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for clstm.lstms.1.conv_h.weight: copying a param with shape torch.Size([64, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 64, 3, 3]).
	size mismatch for clstm.lstms.1.conv_h.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.1.conv_c.weight: copying a param with shape torch.Size([48, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 64, 3, 3]).
	size mismatch for clstm.lstms.1.conv_c.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.1.conv_m.weight: copying a param with shape torch.Size([48, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 128, 3, 3]).
	size mismatch for clstm.lstms.1.conv_m.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.1.conv_x.weight: copying a param with shape torch.Size([112, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([448, 128, 3, 3]).
	size mismatch for clstm.lstms.1.conv_x.bias: copying a param with shape torch.Size([112]) from checkpoint, the shape in current model is torch.Size([448]).
	size mismatch for clstm.lstms.1.conv_c2.weight: copying a param with shape torch.Size([64, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 64, 3, 3]).
	size mismatch for clstm.lstms.1.conv_c2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.1.conv_o.weight: copying a param with shape torch.Size([16, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for clstm.lstms.1.conv_o.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for clstm.lstms.1.conv_h2.weight: copying a param with shape torch.Size([16, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 128, 1, 1]).
	size mismatch for clstm.lstms.1.conv_h2.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for clstm.lstms.2.ln_h.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.2.ln_h.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.2.ln_c.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.2.ln_c.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.2.ln_m.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.2.ln_m.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.2.ln_x.weight: copying a param with shape torch.Size([224]) from checkpoint, the shape in current model is torch.Size([448]).
	size mismatch for clstm.lstms.2.ln_x.bias: copying a param with shape torch.Size([224]) from checkpoint, the shape in current model is torch.Size([448]).
	size mismatch for clstm.lstms.2.ln_c2.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.2.ln_c2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.2.ln_o.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for clstm.lstms.2.ln_o.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for clstm.lstms.2.conv_h.weight: copying a param with shape torch.Size([128, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 64, 3, 3]).
	size mismatch for clstm.lstms.2.conv_h.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.2.conv_c.weight: copying a param with shape torch.Size([96, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 64, 3, 3]).
	size mismatch for clstm.lstms.2.conv_c.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.2.conv_m.weight: copying a param with shape torch.Size([96, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 64, 3, 3]).
	size mismatch for clstm.lstms.2.conv_m.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.2.conv_x.weight: copying a param with shape torch.Size([224, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([448, 64, 3, 3]).
	size mismatch for clstm.lstms.2.conv_x.bias: copying a param with shape torch.Size([224]) from checkpoint, the shape in current model is torch.Size([448]).
	size mismatch for clstm.lstms.2.conv_c2.weight: copying a param with shape torch.Size([128, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 64, 3, 3]).
	size mismatch for clstm.lstms.2.conv_c2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.2.conv_o.weight: copying a param with shape torch.Size([32, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for clstm.lstms.2.conv_o.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for clstm.lstms.2.conv_h2.weight: copying a param with shape torch.Size([32, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 128, 1, 1]).
	size mismatch for clstm.lstms.2.conv_h2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for clstm.lstms.3.ln_h.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.3.ln_h.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.3.ln_c.weight: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.3.ln_c.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.3.ln_m.weight: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.3.ln_m.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.3.ln_x.weight: copying a param with shape torch.Size([112]) from checkpoint, the shape in current model is torch.Size([448]).
	size mismatch for clstm.lstms.3.ln_x.bias: copying a param with shape torch.Size([112]) from checkpoint, the shape in current model is torch.Size([448]).
	size mismatch for clstm.lstms.3.ln_c2.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.3.ln_c2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.3.ln_o.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for clstm.lstms.3.ln_o.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for clstm.lstms.3.conv_h.weight: copying a param with shape torch.Size([64, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 64, 3, 3]).
	size mismatch for clstm.lstms.3.conv_h.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.3.conv_c.weight: copying a param with shape torch.Size([48, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 64, 3, 3]).
	size mismatch for clstm.lstms.3.conv_c.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.3.conv_m.weight: copying a param with shape torch.Size([48, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 64, 3, 3]).
	size mismatch for clstm.lstms.3.conv_m.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for clstm.lstms.3.conv_x.weight: copying a param with shape torch.Size([112, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([448, 64, 3, 3]).
	size mismatch for clstm.lstms.3.conv_x.bias: copying a param with shape torch.Size([112]) from checkpoint, the shape in current model is torch.Size([448]).
	size mismatch for clstm.lstms.3.conv_c2.weight: copying a param with shape torch.Size([64, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 64, 3, 3]).
	size mismatch for clstm.lstms.3.conv_c2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.lstms.3.conv_o.weight: copying a param with shape torch.Size([16, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for clstm.lstms.3.conv_o.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for clstm.lstms.3.conv_h2.weight: copying a param with shape torch.Size([16, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 128, 1, 1]).
	size mismatch for clstm.lstms.3.conv_h2.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for clstm.ghu.ln_x.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.ghu.ln_x.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.ghu.ln_z.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.ghu.ln_z.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.ghu.conv_z.weight: copying a param with shape torch.Size([16, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 128, 3, 3]).
	size mismatch for clstm.ghu.conv_z.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for clstm.ghu.conv_x.weight: copying a param with shape torch.Size([16, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 128, 3, 3]).
	size mismatch for clstm.ghu.conv_x.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([256]).

**Comment by songhune** [comment]
I tried my best,but forgive me, I couldn't manage it...
@Xihaier , I cannot understand the trained parameter stands for, isn't that supposed to point 'predawn' class?
in [https://github.com/NESAP-STL/nesap-stl/blob/master/models/predrnn_pp.py](url)

**Comment by songhune** [comment]
solution: `model.load_state_dict(checkpoint,strict=False)`

**Comment by songhune** [comment]
1. assemble preprocessing in handling sea dataset(w/o cutting lat/long)
2. manage evaluation function
3. (advanced) adopt ConvLSTM
